spring.application.name=ailml
# Database URL
spring.datasource.url=jdbc:mysql://localhost:3306/aiml_tut

# Database username
spring.datasource.username=root

# Database password
spring.datasource.password=Chandu@1502

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console
spring.jpa.show-sql=true

# MySQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Format SQL queries
spring.jpa.properties.hibernate.format_sql=true
